let a = [
    {
        "id": 1116,
        "name": "PUPA",
        "artist": "Morimori Atsushi",
        "keyType": "FOUR",
        "difficulty": "SHD",
        "category": "2021",
        "level": 19,
        "rank": 6,
        "bestScore": 1101781,
        "totalNote": 1781,
        "addTime": "2021-08-16 02:06:00",
        "description": null
    },
    {
        "id": 944,
        "name": "Identity part 2",
        "artist": "SHK",
        "keyType": "FOUR",
        "difficulty": "SHD",
        "category": "O2JAM",
        "level": 19,
        "rank": 5,
        "bestScore": 1102667,
        "totalNote": 2667,
        "addTime": "2021-08-16 02:06:00",
        "description": null
    },
    {
        "id": 1128,
        "name": "MAX301",
        "artist": "NAOKI underground",
        "keyType": "FOUR",
        "difficulty": "SHD",
        "category": "PP",
        "level": 19,
        "rank": 5,
        "bestScore": 1101874,
        "totalNote": 1874,
        "addTime": "2021-08-16 02:06:00",
        "description": null
    },
    {
        "id": 1148,
        "name": "Lucid",
        "artist": "yak_won",
        "keyType": "FOUR",
        "difficulty": "SHD",
        "category": "2013",
        "level": 19,
        "rank": 4,
        "bestScore": 1102411,
        "totalNote": 2411,
        "addTime": "2021-08-16 02:06:00",
        "description": null
    },
    {
        "id": 1252,
        "name": "R.F.C. II",
        "artist": "ND Lee",
        "keyType": "FOUR",
        "difficulty": "SHD",
        "category": "PP",
        "level": 19,
        "rank": 4,
        "bestScore": 1103000,
        "totalNote": 3000,
        "addTime": "2021-08-16 02:06:00",
        "description": null
    },
    {
        "id": 712,
        "name": "ULTIMATUM",
        "artist": "Cosmograph",
        "keyType": "FOUR",
        "difficulty": "SHD",
        "category": "2021",
        "level": 19,
        "rank": 4,
        "bestScore": 1102000,
        "totalNote": 2000,
        "addTime": "2021-08-16 02:06:00",
        "description": null
    },
    {
        "id": 1208,
        "name": "ATOPY",
        "artist": "SANY-ON",
        "keyType": "FOUR",
        "difficulty": "SHD",
        "category": "PP",
        "level": 19,
        "rank": 3,
        "bestScore": 1101812,
        "totalNote": 1812,
        "addTime": "2021-08-16 02:06:00",
        "description": null
    },
    {
        "id": 1200,
        "name": "Black Dragon",
        "artist": "Memme",
        "keyType": "FOUR",
        "difficulty": "SHD",
        "category": "O2JAM",
        "level": 19,
        "rank": 2,
        "bestScore": 1102036,
        "totalNote": 2036,
        "addTime": "2021-08-16 02:06:00",
        "description": null
    },
    {
        "id": 1244,
        "name": "Backfire",
        "artist": "Roy Mikelate (feat.Sobrem)",
        "keyType": "FOUR",
        "difficulty": "SHD",
        "category": "PP",
        "level": 19,
        "rank": 1,
        "bestScore": 1101658,
        "totalNote": 1658,
        "addTime": "2021-08-16 02:06:00",
        "description": null
    }
]

export default a